input: input.jar
output: output.jar
libs: []

general:
  strip:
    enabled: true
    excluded: []
    included: []
    iterations: 1
strings:
  tostring:
    enabled: false
    excluded: []
    included: []
    iterations: 1
misc:
  vars:
    enabled: true
    excluded: []
    included: []
    iterations: 1
  inliner:
    enabled: false
    excluded: []
    included: []
    iterations: 1
    maxPasses: 10
    remove-unused-methods: false
  checksum:
    enabled: false
    excluded: []
    included: []
    iterations: 1
    randomHolders: false
    holders: []
    targets:
      - Main
    reobf: true
    methodName: "run"
    reduced: false
  packer:
    enabled: false
    excluded: []
    included: []
    iterations: 1
    resource-name: '/'
    class-name: ~/
    class-super-name: random
    reobf: true
    forge: true
natives:
  constantpool:
    enabled: true
    excluded: []
    included: []
    iterations: 1
  codehider:
    enabled: true
    excluded: []
    included: []
    iterations: 1